### ISSUE TITLE
Document the pre-commit hook

### ISSUE THREAD

**Issue by WilliamJamieson** [scientific-python/repo-review#107]
Pull request #48 added the ability to run this tool itself as a pre-commit hook. However, aside from the `.pre-commit-hooks.yaml` file and #48, there is no mention of this feature in documentation. It would be good to document that this is possible including a sample pre-commit configuration to enable use of this tool. As users may want a of automatically enforcing the very suggestions this tool makes.

**Comment by henryiii** [comment]
https://repo-review.readthedocs.io/en/latest/intro.html#pre-commit

Or do you mean something else?

**Comment by WilliamJamieson** [comment]
Yes that is exactly what I was thinking, but I missed it. Maybe a link from the README directly to that page so that it is easier to discover?
