### ISSUE TITLE
docs: describe install methods

### ISSUE THREAD

**Issue by mwtoews** [scientific-python/repo-review#148]
This is possibly a transient issue, but trying to install on py310 or py312 in a venv on linux yields the same error:
```bash
$ pipx run sp-repo-review .
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mtoews/.local/pipx/.cache/036cea750998512/lib/python3.12/site-packages/repo_review/__main__.py", line 11, in <module>
    import click as orig_click
ModuleNotFoundError: No module named 'click'
$ pip install click
Requirement already satisfied: click in /tmp/py312/lib/python3.12/site-packages (8.1.7)
```

**Comment by henryiii** [comment]
You need to install `repo-review[cli]`.

In WebSssembly, you don’t need/want click.

**Comment by mwtoews** [comment]
Should the [docs](https://repo-review.readthedocs.io/en/latest/intro.html#installing) describe how to install for CLI? It's sort-of there, but it perhaps needs to be more direct.

This seems to work:
```
pip install repo-review[cli] sp-repo-review
```

**Comment by henryiii** [comment]
Yes, they should.
