### ISSUE TITLE
VPP001: Error: `tool.ruff.lint` cannot be validated by any definition

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [scientific-python/repo-review#232]
See:
https://learn.scientific-python.org/development/guides/repo-review/?repo=pypa%2Fsetuptools_scm&branch=main

The error message is unclear, I think the failure originates [here](https://github.com/pypa/setuptools_scm/blob/4d0d50ba994756cc9d2bae1c9cd730d2da491448/pyproject.toml#L124-L128):
```yaml
[tool.ruff.lint.isort]
force-single-line = true
from-first = false
lines-between-types = 1
order-by-type = true
```

**Comment by henryiii** [comment]
Are one of those fairly new? We probably need to bump

**Comment by DimitriPapadopoulos** [comment]
None of these settings is very recent, the most recent is `from-first` from 2023 (https://github.com/astral-sh/ruff/pull/8663).


In the error message, the `isort` key is almost empty:
```
    'isort':
      at least one of the following:
        - {}
        - {type: null}
```
Is that expected?

**Comment by henryiii** [comment]
Hard to check on my phone, is it in here: https://json.schemastore.org/ruff.json

**Comment by DimitriPapadopoulos** [comment]
It points to the `IsortOptions` definitions:

![Screen Capture](https://github.com/user-attachments/assets/7d3a7020-3e5e-4da9-98f6-1a9c34259275)

**Comment by henryiii** [comment]
It's mad about

```toml
lint.select = ["E", "F", "B", "U", "YTT", "C", "DTZ", "PYI", "PT", "I", "FURB", "RUF"]
```

I think because it has preview only selections in it.

**Comment by henryiii** [comment]
The issue is "U" is not a valid code. "UP" is the correct code. See https://github.com/pypa/setuptools_scm/pull/1064.

**Comment by DimitriPapadopoulos** [comment]
What got me confused is that there were 2 error messages for the same issue;
- RF103: pyupgrade must be selected. Must select the pyupgrade UP checks.
- VPP001: Error: tool.ruff.lint cannot be validated by any definition

The error message could be more helpful (perhaps show the actual invalid code).

**Comment by henryiii** [comment]
For validation, that's handled by validate-pyproject, maybe the error message can be improved there (it's from fastjsonshema). For our end (sp-repo-review, that is), `RF103: pyupgrade must be selected. Must select the pyupgrade UP checks.` described exactly what was missing (no `UP` code).

**Comment by DimitriPapadopoulos** [comment]
Because `RF103` had already been raised about the `UP` typo, I was misled into looking elsewhere for the `VPP001` cause.

The same root cause should not result into different error messages, especially without enough details to clearly identify the root cause (at least a line number).

**Comment by fedorov** [comment]
I am experiencing the same issue here: https://github.com/ImagingDataCommons/idc-index/actions/runs/17810608557/job/50633246476?pr=174. I cannot figure it out, would appreciate any suggestions!

**Comment by jcfr** [comment]
@fedorov  I am looking into the issue associated with `idc-index` 🚀

**Comment by fedorov** [comment]
Thank you JC!

Is there anything that can be done for those poor souls who do not have someone like you to come to the rescue?

For the record, I did try coding assistants - Copilot, Perplexity and Claude - and neither one was of any use in solving this. With my prompts, anyway...

**Comment by henryiii** [comment]
This means that you’re using something that ruff has deprecated. I would recommend either running rough manually or using the `-v` flag to pre-commit and seeing if rough goes a warning about whatever it is that has changed.

Sadly, the schema validation from validate-pyproject doesn’t have very good error messages.
