### ISSUE TITLE
Code blocks are rendered in bright white

### ISSUE THREAD

**Issue by kurtmckee** [scientific-python/repo-review#249]
Hello! I'm creating a repo-review plugin and wanted to include a Markdown code block in the error results. However, the output renders very harshly in the terminal and is not visually accessible (note that the hyphens are not visible due to the colors in use):

> ![image](https://github.com/user-attachments/assets/36117e28-7217-45da-8f3e-e9e742ab6f89)

The `.check()` string that produced this includes this Markdown code:

````markdown
```yaml
- repo: "meta"
  hooks:
    - id: "check-hooks-apply"
    - id: "check-useless-excludes"
```
````

I don't think this is related to my plugin, but rather the default syntax highlighting used in the repo-review framework.

**Comment by henryiii** [comment]
I think we can't detect the terminal color scheme, and Rich forces you to pick a fixed pigments theme for code blocks, so I picked the light one because I thought it was more readable. Unless that changes, we are kind of stuck. You'd need to covert a Pygments color theme (256 fixed colors) into the 16 terminal settable colors.

**Comment by henryiii** [comment]
From my little test, it looks like `ansi_light` and `ansi_dark` might both do exactly the same thing and work?

```python
#!/usr/bin/env uv run --quiet

# /// script
# dependencies = ["rich"]
# ///

import sys

from rich.console import Console
from rich.markdown import Markdown
from rich.syntax import Syntax


THEME = sys.argv[1]
MARKDOWN = """
# This is an h1

Rich can do a pretty *decent* job of rendering markdown.

1. This is a list item
2. This is another list item

```python
from rich.console import Console
from rich.markdown import Markdown

def f():
    return 42
```

```yaml
- repo: "meta"
  hooks:
    - id: "check-hooks-apply"
    - id: "check-useless-excludes"
```
"""

console = Console()
md = Markdown(MARKDOWN, code_theme=THEME)
console.print(md)
```

**Comment by henryiii** [comment]
Released 0.11.3 with the fix, thanks!

**Comment by henryiii** [comment]
(also added a similar fix to https://github.com/scikit-hep/uproot-browser when it gives example code ;) )

**Comment by kurtmckee** [comment]
Nice! Thank you so much!
