### ISSUE TITLE
Is it possible to mark a check as skipped by default?

### ISSUE THREAD

**Issue by kurtmckee** [scientific-python/repo-review#250]
Hello!

I'm writing a plugin for repo-review and realized it might be more generally applicable. However, I'm wanting to introduce some opinionated checks that others might not want on by default ("the tool config getting checked should have thus-and-such enabled").

I think this is analogous to flake8's warnings, not all of which are enabled by default.

My hope is that the plugin can contain those checks, and that I can write a super-plugin (like sp-repo-review) that pulls in all of the generally-applicable stuff and specifies that all of the opinionated checks should be turned on).

Is this currently possible?

**Comment by henryiii** [comment]
I considered this for a while, but never came up on a good way to do it. There are two options I know of currently: flake8-style `X9*` numbers could require opt-in (including via `"X9"`) was what I was considering, but Ruff was starting to become popular and it seemed it didn't do this. And then there's Ruff-style, which has a default set, but any opting in opts into the full set of whatever you opted into, though it does specially handle prefixes (so "T20" and "T" can be different, for example). It also has extra checks behind a `--preview` flag.

Ruff still doesn't have a "family of good checks" concept, which might be related to what we might want to design here.

I'd be open to helping work on this if we can come up with a good design.

**Comment by kurtmckee** [comment]
This answers my question, thanks!

I think that if I release a plugin with a prefix, like Jared Combs' `jaraco.*` or Barry Warsaw's `flufl.*` package prefixes, then I don't have to worry so much about accommodating others' tastes.

Thanks for your time and support, and for your work on repo-review!
